// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package friberg

import (
	"friberg/api/friberg"
)

type ControllerV1 struct{}

func NewV1() friberg.IFribergV1 {
	return &ControllerV1{}
}
