// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package room

import (
	"friberg/api/room"
)

type ControllerSocket struct{}

func NewSocket() room.IRoomSocket {
	return &ControllerSocket{}
}

type ControllerRoom struct{}

func NewRoom() room.IRoomRoom {
	return &ControllerRoom{}
}
